# Generated by Django 4.1 on 2022-08-28 15:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=32, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('mobile', models.CharField(max_length=11, verbose_name='号码')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '银'), (2, '金'), (3, '铂金'), (4, '钻石')], verbose_name='级别')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未启用'), (1, '启用')], default=0, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('pwd', models.CharField(max_length=64, verbose_name='密码')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.department', verbose_name='部门')),
            ],
        ),
    ]
