# Generated by Django 4.1 on 2022-08-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userinfo_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='account',
            field=models.CharField(default='bruce', max_length=16, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
