# Generated by Django 4.1 on 2022-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_userinfo_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='account',
            field=models.CharField(max_length=16, verbose_name='用户名'),
        ),
    ]
