# Generated by Django 4.1 on 2022-09-03 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_userinfo_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('level', models.PositiveSmallIntegerField(choices=[(3, '临时'), (1, '普通'), (2, '重要')], default=1, verbose_name='级别')),
                ('title', models.CharField(max_length=12, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详细信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='负责人')),
            ],
        ),
    ]
