# Generated by Django 4.1 on 2022-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '普通'), (3, '临时'), (2, '重要')], default=1, verbose_name='级别'),
        ),
    ]
