# Generated by Django 4.1 on 2022-09-04 16:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_task_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(2, '重要'), (3, '临时'), (1, '普通')], default=1, verbose_name='级别'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('oid', models.CharField(max_length=32, verbose_name='订单号')),
                ('title', models.CharField(max_length=16, verbose_name='名称')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '已支付'), (2, '未支付')], default=2, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='用户')),
            ],
        ),
    ]
