# Generated by Django 4.1 on 2022-09-21 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_task_level_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.PositiveSmallIntegerField(verbose_name='年龄')),
                ('avatar', models.FileField(max_length=128, upload_to='', verbose_name='头像')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '普通'), (3, '临时'), (2, '重要')], default=1, verbose_name='级别'),
        ),
    ]
