# Generated by Django 4.1 on 2022-09-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_avatar_alter_task_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.FileField(max_length=128, upload_to='avatar/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(2, '重要'), (3, '临时'), (1, '普通')], default=1, verbose_name='级别'),
        ),
    ]
