# Generated by Django 4.1 on 2022-09-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_avatar_avatar_alter_task_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.FileField(default=1, max_length=128, upload_to='depart_logo', verbose_name='logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(2, '重要'), (1, '普通'), (3, '临时')], default=1, verbose_name='级别'),
        ),
    ]
